# Generated by Django 4.1.1 on 2022-09-14 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_dbtest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dbtest',
        ),
    ]
