# Generated by Django 4.1.1 on 2022-09-15 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_delete_dbtest'),
    ]

    operations = [
        migrations.CreateModel(
            name='input_Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('required_Time', models.DurationField()),
                ('priority', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='input_Timerange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=100)),
                ('start_Date', models.DateTimeField()),
                ('end_Date', models.DateTimeField()),
            ],
        ),
    ]
